package file

import (
	"fmt"
	"os"
	"path/filepath"
)

func CreateSshConfig(sshFilename string) error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		fmt.Println("Error getting home directory:", err)
		return err
	}

	sshDir := filepath.Join(homeDir, ".ssh")

	configContent := `# Config Generated By switch-git-account
Host github.com
	HostName github.com
	User git
	UseKeychain yes
   	AddKeysToAgent yes
	IdentityFile ~/.ssh/`

	configContent += sshFilename

	err = createFile(sshDir, "config", configContent)
	if err != nil {
		fmt.Println("Error creating ssh config file:", err)
		return err
	}

	return nil
}

func BackupExistingSshConfig() error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		fmt.Println("Error getting home directory:", err)
		return err
	}

	sshDir := filepath.Join(homeDir, ".ssh")

	err = backupExistingFile(sshDir, "config")
	if err != nil {
		fmt.Println("Error backing up ssh config file:", err)
		return err
	}

	return nil
}
